Repository Hands-Up-Card-Open/HandsUpForServer, pull requests merged in 2022-06, with the labels that each got.

#21 HUCO 146, 147 - Delete Card and Category from DB
  controllers/cardController.js
  controllers/categoryController.js
  models/cardModel.js
  models/categoryModel.js
  routes/card.js
  routes/category.js
Labels: enhancement

#22 Huco 153 - create getting "전체" category's card list
  controllers/cardController.js
  models/cardModel.js
  routes/card.js
Labels: enhancement

#24 Huco 155 - Delete Card Image from Storage
  controllers/cardController.js
  controllers/categoryController.js
  models/cardModel.js
  routes/card.js
Labels: enhancement

#25 HUCO-142 | [ci] setting ci/cd environment
  Dockerfile
  Jenkinsfile
  deployment.yaml
  main.js
  package.json
Labels: enhancement

#26 Develop to main branch
  Dockerfile
  Jenkinsfile
  config/db.js
  controllers/authController.js
  controllers/cardController.js
  controllers/categoryController.js
  controllers/gameController.js
  deployment.yaml
  main.js
  models/authModel.js
  models/cardModel.js
  models/categoryModel.js
  models/gameModel.js
  modules/pool.js
  package-lock.json
  package.json
  routes/auth.js
  routes/card.js
  routes/category.js
  routes/game.js
Labels: enhancement

#42 Huco 164 - create secret about api key & db pw
  Dockerfile
  deployment.yaml
Labels: enhancement

#44 HUCO-164 | [chore] delete not using values
  deployment.yaml
Labels: ci/cd

#45 Delete not using values
  deployment.yaml
Labels: ci/cd, main merge

#46 HUCO-164 | [chore] move env values to backend-secret
  Dockerfile
Labels: ci/cd

#47 Move env values to backend-secret
  Dockerfile
Labels: ci/cd, main merge

#50 HUCO-170 | [fix] add httpsAgent keepAlive
  controllers/gameController.js
Labels: bug

#51 Add httpsAgent keepAlive
  controllers/gameController.js
Labels: bug, main merge

#52 HUCO-170 | [fix] change https to http
  controllers/gameController.js
Labels: bug

#53 Change https to http
  controllers/gameController.js
Labels: bug, main merge

#54 HUCO-170 | [fix] add http module in game controller
  controllers/gameController.js
Labels: bug

#55 Add http module in game controller
  controllers/gameController.js
Labels: bug, main merge
