Repository Hands-Up-Card-Open/HandsUpForServer, pull requests merged in 2022-05, with the labels that each got.

#11 Huco 108 - Text Detection Using Google Vision API & Send Result to Unity
  controllers/gameController.js
  main.js
  models/gameModel.js
Labels: enhancement

#12 Huco 99 - Get All Custom Category/Card using user id and category id
  controllers/cardController.js
  controllers/categoryController.js
  models/cardModel.js
  models/categoryModel.js
  package-lock.json
  package.json
  routes/card.js
  routes/category.js
Labels: bug, enhancement

#13 HUCO-113 | [fix] fix the error of image uploading problem
  controllers/cardController.js
  models/cardModel.js
Labels: bug

#14 Huco 132 - Get public access categories
  controllers/categoryController.js
  models/categoryModel.js
  routes/category.js
Labels: enhancement

#16 HUCO-136 | [feat] create getting customcards not using user_id function
  controllers/cardController.js
  models/cardModel.js
  routes/card.js
Labels: enhancement

#17 HUCO 139 - Edit Card
  controllers/cardController.js
  models/cardModel.js
  routes/card.js
Labels: enhancement

#18 HUCO-139 | [fix] fix update condition, delete affectedRows
  controllers/authController.js
  controllers/cardController.js
  controllers/categoryController.js
Labels: bug

#19 Huco 145 - Update shared_category_user_info table & Add new api field - is_shared, is_new
  controllers/cardController.js
  controllers/categoryController.js
  models/cardModel.js
  models/categoryModel.js
Labels: enhancement
